### ISSUE TITLE
indentation of comments before empty line

### ISSUE THREAD

**Issue by DavidOstrozlik** [sspooky13/yaml-standards#14]
**Which version(s) is affected**: ^4.0.0

**Description**

Yaml standards don't work with new lines after comment. The suggest a change to remove all indentation before the comment. see Additional information

**How to reproduce**

**Possible Solution**

**Additional information**

eg. this:
```yaml
    ObjectCalisthenics\Sniffs\Files\FunctionLengthSniff:
        maxLength: 60
        #sdkjfhsdkjfhsk

    ObjectCalisthenics\Sniffs\Metrics\PropertyPerClassLimitSniff:
        maxCount: 30
``` 

suggests this:
```yaml
     ObjectCalisthenics\Sniffs\Files\FunctionLengthSniff:
         maxLength: 60
-        #sdkjfhsdkjfhsk
+#sdkjfhsdkjfhsk
 
     ObjectCalisthenics\Sniffs\Metrics\PropertyPerClassLimitSniff:
         maxCount: 30
```
