### ISSUE TITLE
bad check/fix multidimensional array

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#26]
**Which version(s) is affected**: all

**Description**
If you create multidimensional array without array key then checker/fixer don't work correctly

**How to reproduce**
e.g. this yaml
```yaml
patchesJson6902:
-   target:
        group: extensions
        version: v1beta1
        kind: Ingress
        name: shopsys
    path: ./ingress-patch.yaml
```
checker/fixer want fix to this
```yaml
patchesJson6902:
-   target:
        group: extensions
        version: v1beta1
        kind: Ingress
        name: shopsys
        path: ./ingress-patch.yaml
```
and it's incorrect.
See https://github.com/shopsys/shopsys/pull/539#issuecomment-515050285 for better detail
