### ISSUE TITLE
New standard: Services: unnecessary defined service

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#48]
**Description**
Just idea, in services.yaml can be defined facade but it's not necessary because auto-wire load them, e.g.
```yaml
Foo\BarBundle\:
        resource: '../../**/*{Facade}.php'

FooBarFacade: ~
```
, so it's not necessary that code exists in services.yaml and it can be removed
