### ISSUE TITLE
New standard: Services: arguments are defined gradually or specifically

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#49]
**Description**
Arguments can be defined in 2 ways: gradually or specifically. So, we should observe one way.

**Example**
Gradually
```yaml
Foo\FooBundle\FooFacade:
    arguments:
        - '%arg_1%'
        - '%arg_2%'
        - '%arg_3%'
```

Specifically
```yaml
Foo\FooBundle\FooFacade:
    arguments:
        $pathToDir: '%arg_1%'
        $pathToFile: '%arg_2%'
        $pathToImage: '%arg_3%'
```
