### ISSUE TITLE
New standard: array is defined in one row or multiple rows

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#50]
**Example**
One row
```yaml
foo:
    { bar: baz, qux: quux, quuz: corge }
```

Multiple rows
```yaml
foo:
    bar: baz
    qux: quux
    quuz: corge
```
