### ISSUE TITLE
New standard: dash is in the same line as key

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#51]
**Example**
Same row
```yaml
foo:
    - bar
    - baz: qux
    - { bar: baz, qux: quux, quuz: corge }
```

Separate row
```yaml
foo:
    - 
        bar
    - 
        baz: qux
    - 
        { bar: baz, qux: quux, quuz: corge }
```
