### ISSUE TITLE
Yaml alphabetical: key after dash will be sorted too

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#57]
**Example**
- uncorrect:
```yaml
-   foo: bar
    quux: quuz
    baz: qux
```
- correct:
```yaml
-   baz: qux
    foo: bar
    quux: quuz
```

**Alert**
First https://github.com/sspooky13/yaml-standards/issues/30 must be done
