### ISSUE TITLE
allow build with lowest dependencies

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#6]
**Description**
fix build in travis and appveyor for lowest dependencies 

**Example**
```yaml
environment:
  matrix:
#  - dependencies: lowest
#    php_version: 5.6
  - dependencies: highest
    php_version: 5.6
#  - dependencies: lowest
#    php_version: 7.0
  - dependencies: highest
    php_version: 7.0
#  - dependencies: lowest
#    php_version: 7.1
  - dependencies: highest
    php_version: 7.1
#  - dependencies: lowest
#    php_version: 7.2
  - dependencies: highest
    php_version: 7.2
```
