### ISSUE TITLE
Don't indent comment line ?

### ISSUE THREAD

**Issue by adpeyre** [sspooky13/yaml-standards#67]
Hi,

I think, comment line should be ignored and not idented ?
For example :

```` yaml

framework:
    validation:
        email_validation_mode: html5

        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false

````

What do you think about that ?

Ty

**Comment by sspooky13** [comment]
Hello,
behind idea of checking indent for comment lines is that comment line belongs to next non-blank line. What exactly is issue? Mentioned example or something different? I am trying to understand if issue is all comment lines are sorted by next non-blank line or another specific scenario

**Comment by adpeyre** [comment]
For me, it doesn't make sense to force these comment lines to left.
In this example, `auto_mapping` has to be defined under framework.validation if I uncomment this line.

Good :
```` yaml

framework:
    validation:
        email_validation_mode: html5
        #auto_mapping:
        #    App\Entity\: []

````

Bad :
```` yaml

framework:
    validation:
        email_validation_mode: html5
#auto_mapping:
#    App\Entity\: []

````

**Comment by sspooky13** [comment]
hmm, if you want to preserve comments at end of file you can use options [indentsCommentsWithoutParent: preserved](https://github.com/sspooky13/yaml-standards/blob/master/tests/Model/YamlIndent/resource/fixed/yaml-getting-started-with-preserved-comments.yml) bud yes, this work only for comments at end of file 🤔

I understand what is your issue but I have more scenarios and I have to apply to them as well
```yaml
framework:
    validation:
        email_validation_mode: html5

        # This is separated comment line which one does not belong to next non-blank line
                        # Is this right intended line or belongs to line upper comment line?

# This belongs to next comment line, maybe
        # This comment line belongs to next line because doesn't have blank line, right?
when@test:
    framework:
        validation:
            not_compromised_password: false
```
Simply, I need something logic or guide which comment line belongs to next line or not. I can create line comment, e.g. `# This is comment line !ignoreIndent!` or something like that and this line will be ignored or `!ignoreIndentGroup` and whole group will be ignored but I don't know whether is solution for you 🤔 Try to describe me complexly issue and I don't have any problem add next option for indent checking

**Comment by adpeyre** [comment]
I think it should be better to create a new option for ignoring comment lines like this :

```` yaml
pathToChecker: YamlStandards\Model\YamlIndent\YamlIndentChecker
parameters:
   { indents: 4, indentsCommentsWithoutParent: default, ignoreComment: true }
````
