### ISSUE TITLE
YamlSpacesBetweenGroupsChecker - add option to skip some groups

### ISSUE THREAD

**Issue by sspooky13** [sspooky13/yaml-standards#81]
**Example**
e.g. this looks better
```yaml
parameters:
    app.notifications.email_sender: anonymous@example.com
    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN
    locale: en

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\:
        exclude: '../src/{Entity,Repository,Tests}'
        resource: '../src/*'
```
as this
```yaml
parameters:
    app.notifications.email_sender: anonymous@example.com

    app_locales: en|fr|de|es|cs|nl|ru|uk|ro|pt_BR|pl|it|ja|id|ca|sl|hr|zh_CN

    locale: en

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    App\:
        exclude: '../src/{Entity,Repository,Tests}'
        resource: '../src/*'
```
